fortunka/config/routes.rb
Fortunka::Application.routes.draw do
resources :fortunes do
  resources :comments
  collection do
    get :tags
  end
end
root :to => 'fortunes#index'
match "/auth/:provider/callback" => "sessions#create"
match "/signout" => "sessions#destroy", :as => :signout

end

fortunka/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :fortune
  validates :author, :presence => true
  validates :body, :presence => true
end

fortunka/app/models/fortune.rb
class Fortune < ActiveRecord::Base
 has_many :comments, :dependent => :destroy
end

fortunka/app/models/user.rb
class User < ActiveRecord::Base
def self.create_with_omniauth(auth)
  create! do |user|
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    user.name = auth["user_info"]["name"]
  end
end
end

fortunka/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

fortunka/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter do
    @fortune = Fortune.find(params[:fortune_id])
  end

  def create
    @comment = @fortune.comments.build(params[:comment])
    @comment.save
    respond_to do |format|
      if @fortune.save
        format.html { redirect_to @fortune, notice: 'Fortune was successfully created.' }
        format.json { render json: @fortune, status: :created, location: @fortune }
      else
        format.html { render action: "new" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
    @comment = @fortune.comments.find(params[:id])
  end

  def update
    @comment = @fortune.comments.find(params[:id])
    @comment.update_attributes(params[:comment])
    respond_to do |format|
      if @fortune.update_attributes(params[:fortune])
        format.html { redirect_to @fortune, notice: 'Fortune was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @comment = @fortune.comments.find(params[:id])
    @comment.destroy
       respond_to do |format|
      format.html { redirect_to fortunes_url }
      format.json { head :ok }
    end
  end
end

fortunka/app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  # GET /fortunes
  # GET /fortunes.json
  def index
    @fortunes = Fortune.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fortunes }
    end
  end

  # GET /fortunes/1
  # GET /fortunes/1.json
  def show
    @fortune = Fortune.find(params[:id])
    @comment = Comment.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/new
  # GET /fortunes/new.json
  def new
    @fortune = Fortune.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/1/edit
  def edit
    @fortune = Fortune.find(params[:id])
  end

  # POST /fortunes
  # POST /fortunes.json
  def create
    @fortune = Fortune.new(params[:fortune])

    respond_to do |format|
      if @fortune.save
        format.html { redirect_to @fortune, notice: 'Fortune was successfully created.' }
        format.json { render json: @fortune, status: :created, location: @fortune }
      else
        format.html { render action: "new" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fortunes/1
  # PUT /fortunes/1.json
  def update
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      if @fortune.update_attributes(params[:fortune])
        format.html { redirect_to @fortune, notice: 'Fortune was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fortunes/1
  # DELETE /fortunes/1.json
  def destroy
    @fortune = Fortune.find(params[:id])
    @fortune.destroy

    respond_to do |format|
      format.html { redirect_to fortunes_url }
      format.json { head :ok }
    end
  end
end

fortunka/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def create
  auth = request.env["omniauth.auth"]
  user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
  session[:user_id] = user.id
  redirect_to root_url, :notice => "Signed in!"
end
def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Signed out!"
end




end

fortunka/app/helpers/application_helper.rb
module ApplicationHelper
end

fortunka/app/helpers/comments_helper.rb
module CommentsHelper
end

fortunka/app/helpers/fortunes_helper.rb
module FortunesHelper
end

fortunka/app/helpers/sessions_helper.rb
module SessionsHelper
end

fortunka/app/views/comments/_comment.html.erb
<p><i>Autor:</i> <%= comment.author %></p>
<div class="comment"><i>Body:</i>
  <%= comment.body %>
</div>
<p>
  <%= link_to "Delete", [@fortune, comment], :confirm => "Are you sure?", :method => :delete %> |
  <%= link_to 'Edit', edit_fortune_comment_path(@fortune, comment) %>
</p>

fortunka/app/views/comments/_form.html.erb
<%= simple_form_for [@fortune, @comment] do |f| %>
  <%= f.input :author, :input_html => {:size => 50} %>
  <%= f.input :body, :input_html => {:rows => 4, :cols => 50} %>
  <%= f.button :submit %>
<% end %>

fortunka/app/views/comments/edit.html.erb
<h1>Edit comment</h1>
<%= render :partial => 'form' %>
<p class="links clear">
  <%= link_to 'Show fortune', @comment.fortune %>
</p>

fortunka/app/views/comments/new.html.erb
<% title "New comment" %>
<%= render :partial => 'form' %>
<p class="links clear"><%= link_to 'Back', @comment.fortune %></p>

fortunka/app/views/fortunes/_form.html.erb
<%= simple_form_for(@fortune) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :quotation %>
    <%= f.input :source %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

fortunka/app/views/fortunes/edit.html.erb
<h2>Edit fortune</h2>

<%= render 'form' %>

<%= link_to 'Show', @fortune %> |
<%= link_to 'Back', fortunes_path %>

fortunka/app/views/fortunes/index.html.erb
<%= stylesheet_link_tag    "style_fortunka" %>
<% @fortunes.each do |fortune| %>
<table>
  <tr>
    <th>Quotation</th>
    <th>Source</th>
	<th></th>
<th></th>
<th></th>
  </tr>
  <tr>
    <td id="cytat"><%= fortune.quotation %></td> 
    <td id="zrodlo"><%= fortune.source %></td>
	<td><%= link_to 'Show', fortune %></td>
	<td><%= link_to 'Back', edit_fortune_path(fortune) %></td>
	<td><%= link_to 'Delete', fortune, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
</table>	
<br/>
<% end %>
<h3><%= link_to 'New Fortune', new_fortune_path %></h3>

fortunka/app/views/fortunes/new.html.erb
<h1>New fortune</h1>

<%= render 'form' %>

<%= link_to 'Back', fortunes_path %>

fortunka/app/views/fortunes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Quotation:</b>
  <%= @fortune.quotation %>
</p>

<p>
  <b>Source:</b>
  <%= @fortune.source %>
</p>
<%= link_to 'Edit', edit_fortune_path(@fortune) %> |
<%= link_to 'Back', fortunes_path %>

<div>
<% if @fortune.comments.any? %>
  <h3>Comments</h3>
  <%= render :partial => 'comments/comment', :collection => @fortune.comments %>
<% end %>
</div>
<div>
<h3>Add comment</h3>
<%= render :partial => 'comments/form' %>
</div>

fortunka/app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	  <title>Fortunes</title>
	  <%= stylesheet_link_tag    "application" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	<meta name="description" content="">
	<meta name="author" content="">

	<meta name="viewport" content="width=device-width,initial-scale=1">
	
	<%= stylesheet_link_tag    "style" %>
	<%= javascript_include_tag "modernizr-2.0.min" %>
	<%= javascript_include_tag "respond.min" %>
</head>
<body>
	<div id="header-container">
		<header class="wrapper">
			<h1 id="title">Fortunes</h1>
			<nav>
				<ul>
					<li><a href=".">Main</a></li>
					<li>
					<% if current_user %>
 					<b><li  id="hello"> Hello <%= current_user.name %>!</li></b>
  					<%= link_to "Logout", signout_path %>
					<% else %>
  					<%= link_to "Login with twitter", "/auth/twitter" %>
					<% end %>
					</li>
				</ul>
			</nav>
		</header>
	</div>
	<div id="main" class="wrapper">
		
		<article>
			<header>
				
			</header>
			
			<p><%= yield %></p>
			<footer>
			</footer>
		</article>
	</div>
	<div id="footer-container">
		<footer class="wrapper">
			<h3>Tomasz Majkowski</h3>
		</footer>
	</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/libs/jquery-1.6.2.min.js"><\/script>')</script>

<!-- scripts concatenated and minified via ant build script-->
<%= javascript_include_tag "plugins" %>
<%= javascript_include_tag "scripts" %>
<!-- end scripts-->

<script>
	var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']]; // Change UA-XXXXX-X to be your site's ID
	(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
	g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
	s.parentNode.insertBefore(g,s)}(document,'script'));
</script>

<!--[if lt IE 7 ]>
	<script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
	<script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
<![endif]-->

</body>
</html>